USE [master]
RESTORE DATABASE [WEGOBI_DRGS_FJCCYY] FROM  DISK = N'D:\00145740 CYS\1.日常文件\20260205 昌财数据处理\shujuku\wegobi_drgs_fjccyy.bak' WITH  REPLACE, 
MOVE N'WEGOBI_DRGS_FJCCYY' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY.mdf',  
MOVE N'WEGOBI_DRGS_FJCCYY_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_log.ldf',  NOUNLOAD,  STATS = 5
GO

USE [master]
RESTORE DATABASE [WEGOBI_DRGS_FJCCYY] FROM  DISK = N'D:\00145740 CYS\1.日常文件\20260205 昌财数据处理\shujuku\wegobi_drgs_fjccyy_admin.bak' WITH  REPLACE, 
MOVE N'WEGOBI_DRGS_FJCCYY_ADMIN' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_ADMIN.mdf',  
MOVE N'WEGOBI_DRGS_FJCCYY_ADMIN_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_ADMIN_log.ldf',  NOUNLOAD,  STATS = 5
GO

USE [master]
RESTORE DATABASE [WEGOBI_DRGS_FJCCYY] FROM  DISK = N'D:\00145740 CYS\1.日常文件\20260205 昌财数据处理\shujuku\wegobi_drgs_fjccyy_echarts.bak' WITH  REPLACE, 
MOVE N'WEGOBI_DRGS_FJCCYY_ECHARTS' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_ECHARTS.mdf',  
MOVE N'WEGOBI_DRGS_FJCCYY_ECHARTS_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_ECHARTS_log.ldf',  NOUNLOAD,  STATS = 5
GO

USE [master]
RESTORE DATABASE [WEGOBI_DRGS_FJCCYY] FROM  DISK = N'D:\00145740 CYS\1.日常文件\20260205 昌财数据处理\shujuku\wegobi_drgs_fjccyy_hospital.bak' WITH  REPLACE, 
MOVE N'WEGOBI_DRGS_FJCCYY_HOSPITAL' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_HOSPITAL.mdf',  
MOVE N'WEGOBI_DRGS_FJCCYY_HOSPITAL_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_HOSPITAL_log.ldf',  NOUNLOAD,  STATS = 5
GO

USE [master]
RESTORE DATABASE [WEGOBI_DRGS_FJCCYY] FROM  DISK = N'D:\00145740 CYS\1.日常文件\20260205 昌财数据处理\shujuku\wegobi_drgs_fjccyy_kpi.bak' WITH  REPLACE, 
MOVE N'WEGOBI_DRGS_FJCCYY_KPI' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_KPI.mdf',  
MOVE N'WEGOBI_DRGS_FJCCYY_KPI_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_KPI_log.ldf',  NOUNLOAD,  STATS = 5
GO


USE [master]
RESTORE DATABASE [WEGOBI_DRGS_FJCCYY] FROM  DISK = N'D:\00145740 CYS\1.日常文件\20260205 昌财数据处理\shujuku\wegobi_drgs_fjccyy_portal.bak' WITH  REPLACE, 
MOVE N'WEGOBI_DRGS_FJCCYY_PORTAL' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_PORTAL.mdf',  
MOVE N'WEGOBI_DRGS_FJCCYY_PORTAL_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_PORTAL_log.ldf',  NOUNLOAD,  STATS = 5
GO


USE [master]
RESTORE DATABASE [WEGOBI_DRGS_FJCCYY] FROM  DISK = N'D:\00145740 CYS\1.日常文件\20260205 昌财数据处理\shujuku\wegobi_drgs_fjccyy_quartz.bak' WITH  REPLACE, 
MOVE N'WEGOBI_DRGS_FJCCYY_QUARTZ' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_QUARTZ.mdf',  
MOVE N'WEGOBI_DRGS_FJCCYY_QUARTZ_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_QUARTZ_log.ldf',  NOUNLOAD,  STATS = 5
GO



USE [master]
RESTORE DATABASE [WEGOBI_DRGS_FJCCYY] FROM  DISK = N'D:\00145740 CYS\1.日常文件\20260205 昌财数据处理\shujuku\wegobi_drgs_fjccyy_wechat.bak' WITH  REPLACE, 
MOVE N'WEGOBI_DRGS_FJCCYY_WECHAT' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_WECHAT.mdf',  
MOVE N'WEGOBI_DRGS_FJCCYY_WECHAT_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_WECHAT_log.ldf',  NOUNLOAD,  STATS = 5
GO


USE [master]
RESTORE DATABASE [WEGOBI_DRGS_FJCCYY] FROM  DISK = N'D:\00145740 CYS\1.日常文件\20260205 昌财数据处理\shujuku\wegobi_drgs_fjccyy_drgdaily.bak' WITH  REPLACE, 
MOVE N'WEGOBI_DRGS_FJCCYY_DRGDAILY' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_DRGDAILY.mdf',  
MOVE N'WEGOBI_DRGS_FJCCYY_DRGDAILY_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\WEGOBI_DRGS_FJCCYY_DRGDAILY_log.ldf',  NOUNLOAD,  STATS = 5
GO