-- 查询所有表和所有字段
SELECT 
    TABLE_SCHEMA AS SchemaName,
    TABLE_NAME AS TableName,
		ROW_NUMBER() OVER (PARTITION BY TABLE_NAME	ORDER BY TABLE_NAME) AS ROW_NUMBER,
		DENSE_RANK() OVER (ORDER BY TABLE_NAME) AS DENSE_RANK,
    COLUMN_NAME AS ColumnName,
    DATA_TYPE AS DataType,
    CHARACTER_MAXIMUM_LENGTH AS MaxLength,
    IS_NULLABLE AS IsNullable
FROM 
    INFORMATION_SCHEMA.COLUMNS
where TABLE_NAME not like '%[0-9]%' and TABLE_NAME not like '%bak'
ORDER BY 
    TABLE_NAME, ORDINAL_POSITION;
