DECLARE @DBName NVARCHAR(128) = N'WEGOBI';
DECLARE @LogFileName NVARCHAR(128) = N'WEGOBI_Log'; 
DECLARE @TargetSizeMB INT = 100; 
DECLARE @SQL NVARCHAR(MAX); 

SET @SQL = N'ALTER DATABASE ' + QUOTENAME(@DBName) + N' SET RECOVERY SIMPLE;';
EXEC sp_executesql @SQL;

SET @SQL = N'USE ' + QUOTENAME(@DBName) + N'; DBCC SHRINKFILE (' + QUOTENAME(@LogFileName) + N', ' + CAST(@TargetSizeMB AS NVARCHAR) + N');';
EXEC sp_executesql @SQL;